EXEC = aes-bruteforce

# Rules and targets
all:
	@cd src/ && $(MAKE)
	@cp -f src/$(EXEC) ./

check: all
	@cd tests/ && $(MAKE) check

format:
	clang-format -i -style=file src/*.[ch] tests/*.[ch]

tidy:
	clang-tidy src/*.c -config="" -- -std=c11

clean:
	@cd src/ && $(MAKE) clean
	@cd tests/ && $(MAKE) clean
	@rm -f $(EXEC) *~

help:
	@echo "Usage:"
	@echo "  make [all]\tBuild all"
	@echo "  make check\tRun all the tests"
	@echo "  make format\tReformat the code"
	@echo "  make tidy\tPerform static-analysis on the code"
	@echo "  make clean\tRemove all files generated by make"
	@echo "  make help\tDisplay this help"

# Special rules and targets
.PHONY: all check clean help
